server:
  port: 8080

spring:
  datasource:
    username: root
    password: chenjg
    url: jdbc:mysql://localhost:3306/link?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 6379

logging:
  level:
    spring.review.demo: DEBUG
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml

# 阿里云OSS配置
aliyun:
  oss:
    endpoint: https://oss-cn-guangzhou.aliyuncs.com
    accessKeyId: LTAI5tFuAcUcZFsbWnpLjcWA
    accessKeySecret: nWhzxHgc2Yc8kPvK6JONbJioWmOuCn
    bucketName: lnu-liang-web-tlias
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
  params: count=countSql

